from .mask_rcnn_config import Config
from .cityscape_config import cityscape_class_names, cityscape_name2label, cityscape_id2label, class_mapping_cityscape_to_kitti, CityScapeAnnotation
from .coco_config import coco_class_names, class_mapping_coco_to_kitti